# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: samples.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'samples.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsamples.proto\x12\nsamples.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x03\n\x07Package\x12\x11\n\tdevice_id\x18\x01 \x01(\x0c\x12\x13\n\x0bhardware_id\x18\x02 \x01(\x0c\x12\x0f\n\x07\x64\x61ta_id\x18\x03 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\x12\x30\n\x11\x66ormat_parameters\x18\x05 \x03(\x0b\x32\x15.samples.v2.Parameter\x12.\n\nstarted_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0b\x64uration_us\x18\x07 \x01(\x04\x12-\n\x0ctrigger_type\x18\x08 \x01(\x0e\x32\x17.samples.v2.TriggerType\x12\x16\n\x0etrigger_source\x18\t \x03(\r\x12\x31\n\x12trigger_parameters\x18\n \x03(\x0b\x32\x15.samples.v2.Parameter\x12\x31\n\x12package_parameters\x18\x0b \x03(\x0b\x32\x15.samples.v2.Parameter\x12\x0c\n\x04\x64\x61ta\x18\x0f \x01(\x0cJ\x04\x08\x0c\x10\x0f\"\xc2\x01\n\tParameter\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\nreal_value\x18\x02 \x01(\x01H\x00\x88\x01\x01\x12\x1a\n\rinteger_value\x18\x03 \x01(\x03H\x01\x88\x01\x01\x12\x17\n\nbool_value\x18\x04 \x01(\x08H\x02\x88\x01\x01\x12\x19\n\x0cstring_value\x18\x05 \x01(\tH\x03\x88\x01\x01\x42\r\n\x0b_real_valueB\x10\n\x0e_integer_valueB\r\n\x0b_bool_valueB\x0f\n\r_string_value*w\n\x0bTriggerType\x12\x1c\n\x18TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15TRIGGER_TYPE_PERIODIC\x10\x01\x12\x16\n\x12TRIGGER_TYPE_EVENT\x10\x02\x12\x17\n\x13TRIGGER_TYPE_MANUAL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'samples_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIGGERTYPE']._serialized_start=656
  _globals['_TRIGGERTYPE']._serialized_end=775
  _globals['_PACKAGE']._serialized_start=63
  _globals['_PACKAGE']._serialized_end=457
  _globals['_PARAMETER']._serialized_start=460
  _globals['_PARAMETER']._serialized_end=654
# @@protoc_insertion_point(module_scope)
