# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vstp.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'vstp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nvstp.proto\"U\n\x11VstpRequestHeader\x12\x0b\n\x03req\x18\x01 \x01(\t\x12\x13\n\x0b\x62ody_length\x18\x03 \x01(\r\x12\n\n\x02iv\x18\x05 \x01(\x0c\x12\x12\n\nkeep_alive\x18\x0c \x01(\x08\"B\n\x12VstpResponseHeader\x12\x0b\n\x03res\x18\x01 \x01(\t\x12\x13\n\x0b\x62ody_length\x18\x02 \x01(\r\x12\n\n\x02iv\x18\x03 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vstp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VSTPREQUESTHEADER']._serialized_start=14
  _globals['_VSTPREQUESTHEADER']._serialized_end=99
  _globals['_VSTPRESPONSEHEADER']._serialized_start=101
  _globals['_VSTPRESPONSEHEADER']._serialized_end=167
# @@protoc_insertion_point(module_scope)
