apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: orwell-strip-api
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: orwell-strip-preview
spec:
  stripPrefix:
    prefixes:
      - /preview
